### ISSUE TITLE
Harvest Level Specifics?

### ISSUE THREAD

**Issue by JHNUXER** [marcel0ll/CustomItems#54]
Could you give us some kind of comparison to normal ingame tool harvestlevels please?

**Comment by Cyd007** [comment]
0 = Wooden/Golden Pickaxe
1 = Stone Pickaxe
2 = Iron Pickaxe
3 = Diamond Pickaxe

**Comment by JHNUXER** [comment]
Oh. Thanks. Sorry to bother you.

**Comment by Cyd007** [comment]
Never is a bother. :-) Always happy to help where I can.
