### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Niconoko** [marcel0ll/CustomItems#56]
I'm going to make a helmet and there're some questions to ask...

- First, I'm confused with the base config file, like where exactly do I put the code?
> https://pastebin.com/VNSJdrtm this is what I'm doing at the moment, correct me if I did wrong.

- Second, [creativeTab] = "Custom Items" < Is this necessary to put into the code too?
- Third, please suggest me some advices, thank you :3

**Comment by 0tho** [comment]
1: The code is fine. You just need ot put it inside the right folder. 
2: Not necessary.
3: You could change your code to:
```
{
  "helmets" : {
      ...
   }
}
```
