### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by trollogyadherent** [marcel0ll/CustomItems#64]
Hello, I archive and rehost defunct mod wikis, among other things. As archive.org did not archive the entire CustomItems wiki, would you still happen to have the files? If yes I would like to ask if it is possible to post a zip of the site.

**Comment by marcel0ll** [comment]
If I remember correctly, the last version of the wiki was using Jekyll and was actually hosted here in GH pages.
I will have a look into fixing the dns so that marcel0ll.github.io/CustomItems works as expected. After that, feel free to download it or use the wiki as you wish.

**Comment by marcel0ll** [comment]
The wiki is partially working on https://marcel0ll.github.io/CustomItems/

But internal links are broken, so you have to fill in the URL manually. I will fix it in the following days.

https://marcel0ll.github.io/CustomItems/documentation/blocks

**Comment by marcel0ll** [comment]
Fixed the wiki: https://marcel0ll.github.io/CustomItems/

It should stay operational as long as GH pages exist, but feel free to archive it as you will.
I will close the ticket, but if you find any problems let me know.
